### ISSUE TITLE
About tree and regimes.

### ISSUE THREAD

**Issue by liu-wq** [evee-tools/evee-tools#1]
Dear Jenny Chen,
I have a small problem that takes up a little time. 
How to convert a tree in nwk format to such a format and then mark that node. I know that treeio in Bioperl can be formatted like this, right? What are the principles for marking nodes? Have you considered replacing the tree file with a format similar to that supported by paml or hyphy.

Thanks！
Liu

**Comment by jjenny** [comment]
Hi Liu,

I'm so sorry - I just realized that github had been sending email to my old university address that I no longer have access to and just saw this question. 

If you still need help on this, I like to use the ETE toolkit (http://etetoolkit.org/) for making and manipulating tree files. Unfortunately the tree file I use for these tools is not standard, but it is required by the 'ouch' package which I use for fitting the OU model.  If you have more specific questions making the necessary tree file, please don't hesitate to ask.
